[project]
name = "main_database"
version = "0.1.0"
dependencies = []

[project.optional-dependencies]
dev = ["pytest"]

[tool.pytest.ini_options]
testpaths = ["functions/tests"]
python_files = ["test_*.py"]
